name: build

# on:
#   pull_request:
#     branches:
#       - main

on:
  push:
    branches:
      - "**"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-17
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build, test, package
        run: mvn -B test package

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jar-artifacts
          path: ./target/*.jar

  semgrep-sast:
    name: Semgrep SAST
    needs: build
    runs-on: ubuntu-latest
    permissions:
      security-events: write
      contents: read
    container:
      image: semgrep/semgrep:latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Semgrep and generate SARIF report
        run: semgrep scan --config auto --sarif -o semgrep.sarif || true
      - name: Upload SARIF to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v4
        if: always()
        with:
          sarif_file: semgrep.sarif

  dependency-check-sca:
    name: OWASP Dependency-Check (HTML)
    needs: build
    runs-on: ubuntu-latest
    container:
      image: maven:3.9.9-eclipse-temurin-17
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Dependency-Check (HTML report)
        run: mvn -B dependency-check:check -Dformat=HTML -DsuppressionFiles=dependency-check-suppressions.xml -DfailBuildOnCVSS=11 || true

      - name: Upload Dependency-Check report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependency-check-report
          path: target/dependency-check-report.html

    dast-baseline:
    name: DAST Baseline (OWASP ZAP)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Prepare ZAP rules file
        run: touch zap-rules.tsv

      - name: Start application in background
        run: |
          java -jar target/*.jar &
          sleep 30

      - name: ZAP baseline scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
          target: http://localhost:8080
          rules_file_name: zap-rules.tsv
          cmd_options: "-r zap-baseline-report.html"

      - name: Upload baseline report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-baseline-report
          path: zap-baseline-report.html


  dast-api:
    name: DAST API Scan (OWASP ZAP)
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download jar artifact
        uses: actions/download-artifact@v4
        with:
          name: jar-artifacts
          path: target

      - name: Start application in background
        run: |
          java -jar target/*.jar &
          sleep 30

      - name: ZAP API scan
        uses: zaproxy/action-api-scan@v0.10.0
        with:
          target: http://localhost:8080/v3/api-docs
          format: openapi
          cmd_options: "-r zap-api-report.html"

      - name: Upload API report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-api-report
          path: zap-api-report.html

